version: '3.8'

services:
  mysql:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: FinanceApp
      MYSQL_USER: dbmasteruser
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"